import { Dimensions } from 'react-native';

const grid = {
  unit: Dimensions.get('screen').width / 3 / 7,
};

export default {
  PRIMARY_COLOR: '#444444',
  PRIMARY_BACKGROUND_COLOR: 'whitesmoke',
  PRIMARY_BACKGROUND_FADED: '#e6e6e6',
  SECONDARY_COLOR: 'white',
  SECONDARY_BACKGROUND_COLOR: 'black',
  SECONDARY_BACKGROUND_FADED: '#1a1a1a',
  ACCENTED_COLOR: 'tomato',
  MUTED_COLOR: 'rgba(0,0,0,0.5)',
  PRIMARY_LIST_SEPARATOR_COLOR: 'rgba(255,255,255,0.2)',
  SECONDARY_LIST_SEPARATOR_COLOR: 'rgba(0,0,0,0.2)',
  INPUT_CONTAINER_COLOR: 'white',
  INPUT_CONTAINER_INVERT_COLOR: '#2F2F2F',
  COLOR_PRIMARY: '#3A59FF',
  COLOR_SECONDARY: '#5bd1d7',
  COLOR_SUCCESS: '#00DD00',
  COLOR_ERROR: 'tomato',
  COLOR_INFO: '#6495ed',
  COLOR_WARNING: '#f0ad4e',
  COLOR_STATUS: 'rgba(100,100,100,1)',
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 20,
  FONT_SIZE_XLARGE: 35,
  FONT_FAMILY: 'Quicksand',
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700',
  CONTAINER_PADDING: 20,
  WIDE_BTN_CONTAINER: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: '10%',
    marginBottom: 20,
  },
  BTN_PRIMARY: {
    backgroundColor: '#00204A',
    color: 'white',
    width: '90%',
    borderRadius: 22,
    textAlign: 'center',
    fontSize: 14,
    fontFamily: 'Quicksand-Medium',
    paddingTop: 13,
    paddingBottom: 13,
    overflow: 'hidden',
  },
  BTN_SECONDARY: {
    backgroundColor: '#448EF6',
    color: 'white',
    width: '90%',
    borderRadius: 22,
    textAlign: 'center',
    paddingTop: 13,
    paddingBottom: 13,
    fontSize: 14,
    fontFamily: 'Quicksand-Medium',
    overflow: 'hidden',
  },
  BTN_DEFAULT: {
    backgroundColor: '#cecece',
    color: 'black',
    width: '90%',
    borderRadius: 22,
    textAlign: 'center',
    fontSize: 14,
    fontFamily: 'Quicksand-Medium',
    paddingTop: 13,
    paddingBottom: 13,
    overflow: 'hidden',
  },
  BTN_WARNING: {
    backgroundColor: '#999999',
    color: 'white',
    width: '90%',
    borderRadius: 22,
    textAlign: 'center',
    fontSize: 14,
    fontFamily: 'Quicksand-Medium',
    paddingTop: 13,
    paddingBottom: 13,
    overflow: 'hidden',
  },
  BTN_DANGER: {
    backgroundColor: '#f71616',
    color: 'white',
    width: '90%',
    borderRadius: 22,
    textAlign: 'center',
    fontSize: 14,
    fontFamily: 'Quicksand-Medium',
    paddingTop: 13,
    paddingBottom: 13,
    overflow: 'hidden',
  },
  BTN_SUCCESS: {
    backgroundColor: '#0baa33',
    color: 'white',
    width: '90%',
    borderRadius: 22,
    textAlign: 'center',
    fontSize: 14,
    fontFamily: 'Quicksand-Medium',
    paddingTop: 13,
    paddingBottom: 13,
    overflow: 'hidden',
  },
  PIN_MAIN_CONTAINER: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
};
